# Minimal LIO-SAM config for drone d2 (VLP-16 style LiDAR)
# /**:  applies these parameters to every node that loads this file
/**:
  ros__parameters:
    use_sim_time: true
    N_SCAN: 16
    Horizon_SCAN: 1800
    downsampleRate: 1
    imuTopic: "/d2/imu/data"
    pointCloudTopic: "/d2/points_enriched"
    odomFrame: "d2/odom"
    mapFrame: "d2/map"
    baseLinkFrame: "d2/base_link"
    lidarFrame: "d2/lidar_link"
    extrinsicRot: [1.0, 0.0, 0.0,
                   0.0, 1.0, 0.0,
                   0.0, 0.0, 1.0]
    extrinsicTrans: [0.0, 0.0, 0.12]
    imuAccNoise: 3.9939570888238808e-03
    imuGyrNoise: 1.5636343949698187e-03
    imuAccBiasN: 6.4356659353532566e-05
    imuGyrBiasN: 3.5640318696367613e-05
    imuGravity: 9.80511
    mappingFrequency: 10.0
